---
title: "NMFS Openscapes Mentor Community"
---

Starting in 2021, we have been growing an informal cross-NMFS mentor community; each science center and regional office participating in the Openscapes cohorts has 1-4 mentors that help organize the local cohorts, spearhead communication with with their local leadership, act as a point-person for interested local staff, help identify local needs, and help communicate, or potentially organize, teaching resources for their local staff. Openscapes organizes training and co-working sessions for the mentor group, so that we can all learn from each others experiences and learn new skills together.  

## Mentors

Organizers

* Leads: Julie Lowndes and Stefanie Butland (Openscapes)
* Co-Lead: Eli Holmes (NOAA Fisheries)

FY23 NMFS Openscapes Mentor group

* AFSC: Emily Markowitz, Josh London, Megsie Siple
* NEFSC: Andy Jones, Scott Large
* NWFSC: Eli Holmes, Eric Ward, Erin Steiner
* PIFSC: Amanda Bradford, Juliette Verstaen
* SEFSC: Adyan Rios, Molly Stevens
* SWFSC: Kevin Stierhoff
* OST: Christine Stawitz, Kathryn Doering

# Mentor Community Activities 

## FY24 Oct 2023 to Sept 2024

FY24 will kick off our formal Openscapes mentors cohort for the fiscal year. The  mentors cohort will help guide the Open Data/Open Science/Reproducibility efforts for their FMC and act as mentors for Champions cohorts. The mentors cohort will act as the "Open Science leadership team" for NOAA Fisheries. Participation is year-long and will include leadership and mentoring training. The mentor group is modeled after the [NASA Openscapes Framework approach](https://openscapes.github.io/approach-guide/mentors-framework).   

### October-December 2023: NMFS Mentors Cohort!

**Please join us: nominate yourself in [this Google Form](https://forms.gle/LJF9gTZCX7ThTzSm9) by Sept 23!**   
**["Is this for me?" 5-min slides](https://docs.google.com/presentation/d/1cSLanri2GM_zKYgI4MzzSdwN1U6WIm01atInGeohTJw/edit?usp=sharing)**

Through facilitation and practical training for mentoring, teaching, and coaching, Openscapes will help NMFS mentors strengthen skills and strategies to support colleagues with diverse comfort levels with software and coding, while also strengthening relationships across centers/offices. Through this, mentors will identify and co-create on common resources and activities – such as code or databases for identical tasks or community developed standard practices – so there is less reinventing at each center. 

The FY24 mentor cohort will start with a mentors-only Openscapes Champions cohort (facilated bi-weekly group meetings) during which Openscapes will guide the mentor cohort in discussing the needs and challenges for adoption of Open Science in NMFS and to develop actions to take. The facilitated meeting are vitual and twice monthly. Mentors will also collaborate asynchronously (e.g. Google Chat, GitHub). During the fall session, mentors will learn and practice coaching and mentoring skills in preparation for the winter Champions cohorts. We will also start identifying cross-center roadblocks that mentors can collaborate on throughout the next years. 

#### Proposed timeline & topics  

- **Dates: Twice monthly starting October 17, 2023** 
- **Times: 10:00 - 11:30am PT / 1:00 - 2:30 pm ET**
- **Location: Remotely, via Google Meet**

#### Mentor Calls 

**Mentor Calls** are when we convene as a group to learn and plan. Agendas are accessible to Cohort participants in our Cohort Google Folder (link upcoming); they are also an archive of our live notetaking. 

Date | Mentor Call Topics          
----| ----------------------
10/17 | 1. Openscapes mindset for mentors: What does it mean to be a mentor? What does Open Science at NMFS mean?
10/31 | 2. Common needs across the FMC: Reflect together on what needs/challenges are common across FMC for Open Science adoption? <!---(Pathways like but focused)--->
11/14 | 3. The art of teaching skills <!---(guest lecture by Carpentries?); Guest lecture by Naomi from eScience about the anxiety that people experience and how to be a good mentor for someone. I am just brainstorming on this one!--->
11/28 | 4. Facilitating discussions and developing team culture <!--- (lecture on the Openscapes method of facilitating discussions)? --->
12/12 | 5. Developing strong Open and Collaborative Communities <!--- (guest presentation from someone at ESIP or presentation by Stef on rOpenSci approach?) --->

#### Seaside Chats

**Seaside Chats** are for small-group coworking in weeks alternating between Mentor Calls. Topics are to reflect with your other center mentors in-between cross-center cohort calls. Note multiple FMCs can have Seaside chats together. Organize yourselves in a way that works for you.

Date | Seaside Chat topics
----| ----------------------
Week of 10/23 | Begin work on an Open Science Pathway for your FMC. Where are you at? Where would you like to be? Do you have the info you need to answer this?
Week of 11/6  | Keep working Open Science Pathway with FMC specific discussions of needs/challenges
Week of 11/20 | Cross-FMC discussions of Open Science Pathways and work on shared organizing with GitHub
Week of 12/4. | Discuss ideas and plans for coordinating & engaging staff in Open Science goals

### January-June 2023

From January-May through our bi-weekly meetings we are learning coaching skills with Tara Robertson, a DEI consultant and leadership coach who has [worked with Openscapes since 2021](https://www.openscapes.org/blog/2021/05/27/tara-robertson/). We are learning valuable coaching skills - how to ask open-ended questions, how to listen - that make us better equipped as mentors, teachers, and leaders. When listening as a coach, we're trying to help the other person define their problem and find their solution, outside of our expertise. This is different from mentoring, when we do have an answer within our expertise. Developing these coach listening skills, what questions to ask, and when to use mentoring vs coaching skills, is the focus of our sessions; we are practicing coaching skills together to tackle common challenges and skill-build together.

Our mentor-coach sessions are cross-government, and include Openscapes mentors working within and across their own institutions. 

- NMFS mentors 
- [NASA Openscapes Mentors](https://nasa-openscapes.github.io/mentors.html) 
- [California WaterBoards/Cal EPA mentors](https://cawaterboarddatacenter.github.io/swrcb-openscapes/)
- [Pathways to Open Science mentors](https://openscapes.github.io/pathways-to-open-science/)
- EPA mentors


## 2022

### July-August

The NMFS Openscapes mentor group is meeting bi-weekly. Current focus is on activities surrounding the summer cohorts at SEFSC and Cal EPA.

### Spring 

Mentors and other interested folks across science centers and regional offices met several times to plan and give presentations about NMFS Openscapes efforts to individual science centers and the NMFS Science Board.

### January-March

The AFSC Mentors met bi-weekly during the 2021-2022 AFSC cohort. 

